import contentTypes from './contentTypes';

const [
  string,
  comment,
  identifier,
  rest,
] = contentTypes;

export default ({
  separators: [
    ' ',
    '\n',
    '\t',
  ],
  gfm: {
    ':x:': '❌',
    ':exclamation:': '❗️',
    ':grapes:': '🍇',
    ':watermelon:': '🍉',
    ':abc:': '🔤',
    ':cookie:': '🍪',
    ':thought_balloon:': '💭',
    ':soon:': '🔜',
    ':end:': '🔚',
    ':green_book:': '📗',
    ':blue_book:': '📘',
    ':fist_right:': '🤜',
    ':fist_left:': '🤛',
    ':heavy_plus_sign:': '➕',
    ':heavy_minus_sign:': '➖',
    ':heavy_multiplication_x:': '✖️',
    ':heavy_division_sign:': '➗',
    ':ice_cream:': '🍨',
    ':honey_pot:': '🍯',
    ':eggplant:': '🍆',
    ':checkered_flag:': '🏁',
    ':grinning:': '😀',
    ':crayon:': '🖍',
    ':new:': '🆕',
    ':right_arrow:': '➡️',
    ':thumbsup:': '👍',
    ':thumbsdown:': '👎',
    ':ok_hand:': '👌',
    ':droplet:': '💧',
    ':1234:': '🔢',
    ':100:': '💯',
    ':abcd:': '🔡',
    ':candy:': '🍬',
    ':beer:': '🍺',
    ':arrow_right_hook:': '↪️ ',
    ':no_good:': '🙅',
    ':repeat_one:': '🔂',
    ':repeat:': '🔁',
    ':fast_forward:': '⏩',
    ':next_track_button:': '⏭',
    ':raised_hands:': '🙌',
    ':arrow_forward:': '▶️',
    ':arrow_backward:': '◀️',
    ':rabbit2:': '🐇',
  },
  traditional: {
    '\\': '❌',
    ';': '❗️',
    '{': '🍇',
    '}': '🍉',
    '"': '🔤',
    '`': '🍪',
    '//': '💭',
    '/*': '💭🔜',
    '*/': '🔚💭',
    '/**': '📗',
    '**/': '📗',
    '/***': '📘',
    '***/': '📘',
    '(': '🤜',
    ')': '🤛',
    '+': '➕',
    '-': '➖',
    '*': '✖️',
    '/': '➗',
    'l[': '🍨',
    'd[': '🍯',
    ']': '🍆',
    ':': '🍬',
    unwrap: '🍺',
    main: '🏁',
    print: '😀',
    $: '🖍',
    var: '🖍🆕',
    '->': '➡️',
    true: '👍',
    false: '👎',
    boolean: '👌',
    char: '💧',
    long: '🔢',
    double: '💯',
    string: '🔡',
    if: '↪️',
    else: '🙅',
    for: '🔂',
    while: '🔁',
    range: '⏩',
    step: '⏭',
    '=': '🙌',
    '>': '▶️',
    '>=': '▶️🙌',
    '<': '◀️',
    '<=': '◀️🙌',
    class: '🐇',
  },
  boundary: {
    ':abc:': { contentType: string, endingToken: ':abc:' },
    '"': { contentType: string, endingToken: '"' },
    ':thought_balloon: :soon:': { contentType: comment, endingToken: ':end: :thought_balloon:' },
    '/*': { contentType: comment, endingToken: '*/' },
    ':green_book:': { contentType: comment, endingToken: ':green_book:' },
    '/**': { contentType: comment, endingToken: '**/' },
    ':blue_book:': { contentType: comment, endingToken: ':blue_book:' },
    '/***': { contentType: '', endingToken: '***/' },
    ':thought_balloon:': { contentType: comment, endingToken: '\n' },
    '//': { contentType: comment, endingToken: '\n' },
    ':crayon: :new:': { contentType: identifier, endingToken: 'anything' },
    var: { contentType: identifier, endingToken: 'anything' },
    ':crayon:': { contentType: identifier, endingToken: 'anything' },
    $: { contentType: identifier, endingToken: 'anything' },
  },
  escapeSequence: [
    ':x:',
    '\\',
  ],
});
