import contentTypes from './contentTypes';

const [
  string,
  comment,
  identifier,
  rest,
] = contentTypes;

export default ({
  separators: [
    ' ',
    '\n',
    '\t',
  ],
  gfm: {
    ':x:': '❌',
    ':exclamation:': '❗️',
    ':grapes:': '🍇',
    ':watermelon:': '🍉',
    ':abc:': '🔤',
    ':thought_balloon:': '💭',
    ':soon:': '🔜',
    ':end:': '🔚',
    ':green_book:': '📗',
    ':blue_book:': '📘',
    ':ice_cream:': '🍨',
    ':honey_pot:': '🍯',
    ':eggplant:': '🍆',
    ':checkered_flag:': '🏁',
    ':grinning:': '😀',
    ':crayon:': '🖍',
    ':new:': '🆕',
    ':right_arrow:': '➡️',
    ':abcd:': '🔡',
    ':candy:': '🍬',
    ':beer:': '🍺',
    ':rabbit2:': '🐇',
  },
  traditional: {
    '\\': '❌',
    ';': '❗️',
    '{': '🍇',
    '}': '🍉',
    '(': '🤜',
    ')': '🤛',
    '"': '🔤',
    '//': '💭',
    '/*': '💭🔜',
    '*/': '🔚💭',
    '/**': '📗',
    '**/': '📗',
    '/***': '📘',
    '***/': '📘',
    'l[': '🍨',
    'd[': '🍯',
    ']': '🍆',
    ':': '🍬',
    unwrap: '🍺',
    main: '🏁',
    print: '😀',
    var: '🖍🆕',
    '->': '➡️',
    string: '🔡',
    class: '🐇',
    $: '🖍',
  },
  boundary: {
    ':abc:': { contentType: string, endingToken: ':abc:' },
    '"': { contentType: string, endingToken: '"' },
    ':thought_balloon: :soon:': { contentType: comment, endingToken: ':end: :thought_balloon:' },
    '/*': { contentType: comment, endingToken: '*/' },
    ':green_book:': { contentType: comment, endingToken: ':green_book:' },
    '/**': { contentType: comment, endingToken: '**/' },
    ':blue_book:': { contentType: comment, endingToken: ':blue_book:' },
    '/***': { contentType: '', endingToken: '***/' },
    ':thought_balloon:': { contentType: comment, endingToken: '\n' },
    '//': { contentType: comment, endingToken: '\n' },
    ':crayon: :new:': { contentType: identifier, endingToken: 'anything' },
    var: { contentType: identifier, endingToken: 'anything' },
    ':crayon:': { contentType: identifier, endingToken: 'anything' },
    $: { contentType: identifier, endingToken: 'anything' },
  },
  escapeSequence: [
    ':x:',
    '\\',
  ],
});
